language: node_js
node_js:
- '5'
install: npm install
before_script: npm run dist
script: npm test
before_deploy: echo 'All unit tests passed; Successfull built distribution assets;
  Preparing to deploy Discovery Shared Collection Catalog to AWS.'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: discovery-ui
  env: discovery-ui-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-ui-production
  on:
    repo: NYPL-discovery/discovery-front-end
    branch: master
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: discovery-ui
  env: discovery-ui-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-ui-qa
  on:
    repo: NYPL-discovery/discovery-front-end
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: discovery-ui
  env: discovery-ui-development
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: discovery-ui-development
  on:
    repo: NYPL-discovery/discovery-front-end
    branch: development
after_deploy: echo 'Successfully executed deploy trigger for Discovery Shared Collection
  Catalog on AWS'
env:
  global:
    secure: s/Wksi6nrU6vaBGKVEbmh2Qbaa9adVnQDx5QhcuyxWk61gh27g6KQ+JEkUlaWxChsWLBZM221Kw9xkB0uP6tMHksg6hOxPyO9JwcS3g15hs5b7qph+3Kt7FKpwlXR8T6o880AjdAFuyIr8tLavll4UD6I8cHaZp9BsjxPT6tkn9NQFITQ/3pURtD/wfLHCkeE+QuTHLhBqhHMscTjuuiqmNAimCzE95tteEfgRMh06+TPHfZsItd2OvhjB2MvJtzulPGjIENhl2UFj595Tu5PbfMBBKSRumfSv2MIFGJhKRM1r8e/jviuZfMpbmaCMxxSqj3EFIdFLPA0hEeOvmZ8Scf3VF0M4x6I4lt1AbxVlHWEWimBVqyFsZC8hOSTbfSq9Su1Y9KMYhFPiKjaAdPasg8pcEm5qOEKBzBl84jhiKkj0eSWg1T+nuF8XRaLd6vtV5bVqVaDmO9NCbfx+Or8nordX/++dNfRn85VjlX6wPV5uUR3efvG9QxZSCenv8ai5ohEdT/wKWk7BTJa+MMWUUFKdxTc5WU7vDhH22HYkXKJxV6nVEXm/NGbBgNrzpurb26jTpJmRk9wVL8rz+HvQ3xTPexQlQkexDUeV9ue7EZSkgXqMDbMx3yItuSgTLGwTOBrwlPGh/H6DzGfJOxB3C2Y0LLG67hUaNqQsRRZL8=
