language: node_js
node_js:
- 10.17.0
install: npm rebuild node-sass && npm install
before_script: npm run dist
script: npm test
before_deploy: echo 'All unit tests passed; Successfull built distribution assets;
  Preparing to deploy Discovery Research Catalog to AWS.'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: discovery-ui
  env: discovery-ui-shep-development
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: discovery-ui-development
  on:
    repo: NYPL/discovery-front-end
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: false
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: discovery-ui
  env: DiscoveryUi-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-ui-shep
  on:
    repo: NYPL/discovery-front-end
    branch: production
- provider: elasticbeanstalk
  skip_cleanup: false
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: discovery-ui
  env: DiscoveryUi-10-17-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-ui-shep
  on:
    repo: NYPL/discovery-front-end
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: false
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: discovery-ui
  env: DiscoveryUi-edd-training
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-ui-shep
  on:
    repo: NYPL/discovery-front-end
    branch: accounts
after_deploy: echo 'Successfully executed deploy trigger for Discovery Research Catalog
  on AWS'
env:
  global:
  - secure: ZjvWOeLdpAb48dSAlnOqd4f9Qu9etZ+N8UMyQDcAq8Ckyw6TG0mHIxl+EOcQkYMuyeIjQPPFFYT4xlZU4x9JVmK3UnhlkZrkd81UxkyvugU0Cy5Nq8pnHi1xZPRQXUfNrE16B/NKn+tMvPakOkdhSRSRhDuC4NmsRqEh/ttDyXY2ChmuRCZXrJFY7QoMvDnW+YArEKp0uWl4Xdsnx6o+F2YeWVh5BQgL1PixwKiwrSAbtOnet42r7nBDRAOmseKy5gw4NQGbz0FZBhTUEoou1HnpzWUhR+Voz/znwYIrD7z+/XceBLqxFzei+BOrQKuon9rviYVhlGDBQDwdczLncpor0xUJEFHyTNIna3Fqd1H4EQZuBt3HmFpHHK8olQ46fLPon97XcPQT4t7KihDAvrD7I8I5XJBe8i8vvPdIRePw5pmBcK7s0awEVbf1an7324/+7xg2qAyZz9ccu4cbB7dSgZE2IOpK34//UB0j8SJGAt9X6S3HaeDeKF1Ti8xTgxdWDVq+ccsXgyDMqW5boDxaArZ0oM5JFq+j6XHfPnRLL1EfPzH06FgKai/4MuibxfaQ7NvD9lsAhigtebjzcKyHxh+CYPHbGfvTkFXJNBX/D3aZ4sg96va5XFy8rqR5VGEdBnhJj6Ppzh1EtOIgAhKIwHm1jDooLU41I2DEUYg=
  - secure: Qfnvs1EKEckdxvSnwCvlQE7AvDFOn+bftpX4FbjdFBu5V0C2Tbvs4dCqlm4U3NzpmGccQf7cQ2hX+kcrDcYdhRWrUnbfBa6cgSP/sCybx9macomxu3PFyi7WZMDAh+HdcrTQCEAmqZqmKV+5I65YwdYqD+4fEbUtnRswMHHSRjpVASkKVVr7BLjJB4XDo/YiVDstp0TWAx3aksxK29dRjs1Kg2CQN5Lq+NmyII4c8x+rrtAWtn9B0PEn//v7FheLbcnaqom0cRRU+DXE2MkIbyVLdJ2Sm5/sAd4g2zFPBiRGeMP1AZUj/01pYaom7YTfUGNNtUTKz8jHibTxHDiNkesTC5abdu5786xATHk1CUfTM4yy1EgMGlkyfvF2bmG83qQA2ATYjJyJCK1Qt2uEeJ7pzd/8eJdUvLAw973+JOehfDQCOV1PdYLEgmDCsnJXG1le1okbN+o3Oyag4LDBKzdcCnS13gesPl5qFaiUn2EPFCcfwTcuSeonkmpd1lHSFuuIXxyTOAkWdw31Ks0xGbFfnJN1GJZ+pnfFzOhYnsljeCR7EDdRea6Wuu8a3xLaLWKHoZzE3F49z54Aq1wQm0ARfRHpvZQhV9P7DI8X1mjkkbq+4HC5TuhTjJ8NbnwxguTqabIbl4BJfUJMsLTLd2lbzSD06dtx00GvENISOLE=
  globa:
    secure: G5Zw/OeyuKKODfQBydkl4tBv9xWAgwOEUX3hvJdIXfApXuXkSxp6RpSwA3KO1hYsDwHADsrUKfCKWCmNPDrNeRVTlk6YRoas+984HTqkucQ8xgxmUT6QR+e7dwzWn2prKHO8IlBXv2/9kwCVaC99pXR8xYVkxciCb4JQkJO22FwUBFH08Lo22y81hslES8WXqpSN4PHsxTHlfYPLADuhiVzG9Y51qqPiwQLnfzt52T2FExo1IM6vlUKSkvTwtcxb4X5yj/Y1CAckcmb4pMoQLEsvZUlID+7WgnMYlrVgZsBe5+RaU3EbTLubWGFvtgQy7teSAaMen3hZps/jwU04TLR2mIEomhXqUsynbfb8mNGScowifCJn+QTl+0jK5i8TxC8W84Qb0c4elQpaX2Vp58GjLRZ85897c83huzo+13frJOPoioRST/IJm5Qkw/O63ibYE6VftY0FEAFyukgiiaZ7OHWAymD/dthxuKaA8eeGwXDq8+4pH36sfxDzLD9lxlQyr55gGN3fnhQVchHeQyRz4Ea6hNjDVgBbx8tXPJRLP7QRHKvJy16wVYZ6kEGOujsFWEri2hVIFF0V015eF8cUMU87MGS2Xe/J2JSaDMu5w7ZqwTvzCxftsakT7MkUZsbMrueqH6gbavhCEbXzLOGDXQAeckhCpEf9jXNaqwk=

